### ISSUE TITLE
Adicionando itens no main

### ISSUE THREAD

**Issue by patrickfreiree** [winstedyuri/cursos-pjey#1]
import java.util.Scanner;

public class main {
    public static void main(String[] args) {

        Scanner ler = new Scanner(System.in);

        System.out.println("------------------------------");
        System.out.println("----------Bem Vind@!!---------");
        System.out.println("------------------------------");

        int menu = 0;

        System.out.println("----------- ECOLHA -----------");
        System.out.println("------1 - NOVO POR AQUI-------");
        System.out.println("----- 2 - JA TENHO CADASTRO---");
        System.out.println("------------------------------");

        String escolha1;
        String escolha2;
        System.out.print("Escolha um dos números: ");
        escolha1 = ler.next();
        escolha2 = ler.next();

        Usuario usuario = new Usuario();

        switch (escolha1) {

            case "1":
                System.out.print("Nome do novo discente:");
                usuario.setNome(ler.next());
                System.out.print("CPF:");
                usuario.setCpf(ler.next());
                System.out.print("E-mail:");
                usuario.setEmail(ler.next());

                System.out.print("Deseja fazer mais alguma operação ? (s/n): ");
                String captcha1 = ler.next();
                if ("s".equals(captcha1)) {
                    main(args);
                } else if ("n".equals(captcha1)) {
                    System.out.print("-----Processo finalizado.------");
                    break;
                }

            case "2":
                String cpfDigitado;
                System.out.print("Digite seu CPF: ");
                cpfDigitado = ler.next();
                if (cpfDigitado.equals(cpfDigitado)) {
                    System.out.println("CPF Correto");
                    System.out.println("Tela de acesso permitido");
                    System.out.println("------------------------");

                    do {

                        System.out.println("------------ MENU ------------");
                        System.out.println("--- 1 - Cursos disponíveis ---");
                        System.out.println("--- 2 - Nome Professores -----");
                        System.out.println("--- 0 - Sair -----------------");
                        System.out.println("------------------------------");

                        switch (escolha2){

                        case "1":
                            System.out.println("----- CURSOS OFERTADOS -----");
                            System.out.println("--- 1 - Inglês nivel 1 -----");
                            System.out.println("--- 2 - Inglês nivel 2 -----");
                            System.out.println("--- 3 - Espanhol nivel 1 ---");
                            System.out.println("--- 4 - Espanhol nivel 2 ---");

                        case "2":

                        case "0":

                        }

                    }
                } else {
                    System.out.println("CPF Incorreto");
                    System.out.println("Tela de acesso não permitido");
                    System.out.println("-----------------------------");
                    if ("s".equals(captcha1)) {
                        main(args);
                    } else if ("n".equals(captcha1)) {
                        System.out.print("-----Processo finalizado.------");
                        break;
                    }

                }
        }
    }
}

**Comment by winstedyuri** [comment]
.
